# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v14
      with:
        repositories: '[{ "id": "egovframe", "url": "https://maven.pkg.github.com/atlena/*", "snapshots": { "enabled": "true" } }]'
        servers: ${{secrets.GH_MVN_REPO_USER_INFO}}
    - name: check settings.xml
      run: cat ~/.m2/settings.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy with Maven
      run: mvn -B deploy --file pom.xml
